app: 
  name: app_name
  port: app_port
  env: node_env

default: 
  type: db_type
  host: db_host
  port: db_port
  username: db_username
  password: db_password
  database: db_database

jwt: 
  secret: jwt_secret_key
  expiresTime: expires_time